import { randomUUID } from "node:crypto";
import type { FastifyInstance, FastifyReply, FastifyRequest } from "fastify";
import type { Pool, PoolClient } from "pg";
import { z } from "zod";
import type { ApiConfig } from "../../config/env.js";
import { requirePrincipalFromCookie } from "../auth/authorization.js";
import { AuthError, AuthService, type AuthPrincipal } from "../auth/service.js";

const id = z.object({ employeeId: z.string().uuid() });
const editable = z.object({ fullName:z.string().trim().min(1), employeeNumber:z.string().trim().min(1), status:z.enum(["active","inactive","resigned"]), employmentStatus:z.string().trim().nullable(), organizationalUnitId:z.string().uuid().nullable(), positionId:z.string().uuid().nullable(), employmentType:z.string().trim().nullable(), functionalPosition:z.string().trim().nullable(), structuralPosition:z.string().trim().nullable(), email:z.string().trim().email().nullable(), phone:z.string().trim().max(50).nullable(), education:z.string().trim().nullable(), startedOn:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).nullable(), endedOn:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).nullable(), reason:z.string().trim().min(1).max(500) });
const removal = z.object({ confirmationName:z.string().trim().min(1), reason:z.string().trim().min(1).max(500) });
const keys = ["fullName","employeeNumber","status","employmentStatus","organizationalUnitId","positionId","employmentType","functionalPosition","structuralPosition","email","phone","education","startedOn","endedOn"] as const;

async function dependencies(db: Pool | PoolClient, employeeId: string) {
  return (await db.query<{category:string;count:number}>(`WITH today AS (SELECT (now() AT TIME ZONE 'Asia/Jakarta')::date d), current_revision AS (
 SELECT c.id FROM organization_change_sets c,today WHERE c.status='PUBLISHED' AND c.effective_on<=today.d ORDER BY c.effective_on DESC,c.published_at DESC,c.created_at DESC,c.id DESC LIMIT 1
 ) SELECT category,count(*)::int AS count FROM (
 SELECT 'membership' category FROM organization_memberships x,current_revision c,today WHERE x.change_set_id=c.id AND x.employee_id=$1 AND x.effective_from<=today.d AND (x.effective_to IS NULL OR x.effective_to>=today.d)
 UNION ALL SELECT 'incumbency_employee' FROM organization_incumbencies x,current_revision c,today WHERE x.change_set_id=c.id AND x.employee_id=$1 AND x.effective_from<=today.d AND (x.effective_to IS NULL OR x.effective_to>=today.d)
 UNION ALL SELECT 'incumbency_employee_account' FROM organization_incumbencies x JOIN accounts a ON a.id=x.account_id,current_revision c,today WHERE x.change_set_id=c.id AND a.employee_id=$1 AND a.principal_type='EMPLOYEE' AND x.effective_from<=today.d AND (x.effective_to IS NULL OR x.effective_to>=today.d)
 UNION ALL SELECT 'reporting_override_employee' FROM organization_reporting_overrides x,current_revision c,today WHERE x.change_set_id=c.id AND x.employee_id=$1 AND x.effective_from<=today.d AND (x.effective_to IS NULL OR x.effective_to>=today.d)
 UNION ALL SELECT 'reporting_override_manager' FROM organization_reporting_overrides x,current_revision c,today WHERE x.change_set_id=c.id AND x.manager_employee_id=$1 AND x.effective_from<=today.d AND (x.effective_to IS NULL OR x.effective_to>=today.d)
 UNION ALL SELECT 'legacy_direct_manager' FROM employees x WHERE x.direct_manager_employee_id=$1 AND x.status='active' AND x.removed_at IS NULL
 ) d GROUP BY category ORDER BY category`,[employeeId])).rows;
}

export async function registerEmployeeMasterAdminRoutes(app: FastifyInstance, pool: Pool, config: ApiConfig) {
  if (!config.AUTH_ENCRYPTION_KEY) throw new Error("AUTH_ENCRYPTION_KEY is required for employee master routes");
  const auth = new AuthService(pool,config.AUTH_ENCRYPTION_KEY,config.AUTH_SESSION_TTL_HOURS,config.NODE_ENV==="production");
  const guard=async(r:FastifyRequest,reply:FastifyReply):Promise<AuthPrincipal|null>=>{try{return await requirePrincipalFromCookie(auth,r.headers.cookie,"SUPER_ADMIN");}catch(e){if(e instanceof AuthError){await reply.status(e.statusCode).send({code:e.code,message:e.message});return null;}throw e;}};
  app.get("/admin/employees/:employeeId/source-snapshots",async(r,reply)=>{if(!await guard(r,reply))return;const p=id.safeParse(r.params);if(!p.success)return reply.status(400).send({code:"INVALID_EMPLOYEE_ID"});const rows=await pool.query(`SELECT id,source_filename AS "sourceFilename",source_sheet AS "sourceSheet",imported_at AS "importedAt",unmodeled_source_data AS "unmodeledSourceData" FROM employee_import_source_snapshots WHERE employee_id=$1 ORDER BY imported_at DESC`,[p.data.employeeId]);return reply.send({items:rows.rows.map((x:{importedAt:Date})=>({...x,importedAt:x.importedAt.toISOString()}))});});
  app.patch("/admin/employees/:employeeId",async(r,reply)=>{const actor=await guard(r,reply);if(!actor)return;const p=id.safeParse(r.params),b=editable.safeParse(r.body);if(!p.success||!b.success)return reply.status(400).send({code:"INVALID_EMPLOYEE_EDIT"});const c=await pool.connect();try{await c.query("BEGIN");const before=(await c.query<Record<string,unknown>>(`SELECT full_name AS "fullName",employee_number AS "employeeNumber",status,employment_status AS "employmentStatus",organizational_unit_id AS "organizationalUnitId",position_id AS "positionId",employment_type AS "employmentType",functional_position AS "functionalPosition",structural_position AS "structuralPosition",email,phone,education,started_on::text AS "startedOn",ended_on::text AS "endedOn" FROM employees WHERE id=$1 FOR UPDATE`,[p.data.employeeId])).rows[0];if(!before)throw new Error("NOT_FOUND");const v=b.data;const after={fullName:v.fullName,employeeNumber:v.employeeNumber,status:v.status,employmentStatus:v.employmentStatus,organizationalUnitId:v.organizationalUnitId,positionId:v.positionId,employmentType:v.employmentType,functionalPosition:v.functionalPosition,structuralPosition:v.structuralPosition,email:v.email?.toLowerCase()??null,phone:v.phone,education:v.education,startedOn:v.startedOn,endedOn:v.endedOn};const changedFields=keys.filter(k=>String(before[k]??"")!==String(after[k]??""));await c.query(`UPDATE employees SET full_name=$2,employee_number=$3,status=$4,employment_status=$5,organizational_unit_id=$6,position_id=$7,employment_type=$8,functional_position=$9,structural_position=$10,email=$11,phone=$12,education=$13,started_on=$14,ended_on=$15,updated_at=now() WHERE id=$1`,[p.data.employeeId,...keys.map(k=>after[k])]);await c.query("INSERT INTO access_audit_events (id,actor_account_id,action,entity_type,entity_id,payload) VALUES ($1,$2,'employee.master.updated','employee',$3,$4::jsonb)",[randomUUID(),actor.id,p.data.employeeId,JSON.stringify({before,after,changedFields,reason:v.reason,source:"manual"})]);await c.query("COMMIT");return reply.send({employeeId:p.data.employeeId,accountEmailChanged:false});}catch(e){await c.query("ROLLBACK");return reply.status(e instanceof Error&&e.message==="NOT_FOUND"?404:409).send({code:"EMPLOYEE_EDIT_CONFLICT"});}finally{c.release();}});
  app.post("/admin/employees/:employeeId/remove-preview",async(r,reply)=>{if(!await guard(r,reply))return;const p=id.safeParse(r.params);if(!p.success)return reply.status(400).send({code:"INVALID_EMPLOYEE_ID"});const person=(await pool.query(`SELECT e.full_name AS "fullName",e.removed_at AS "removedAt",a.id AS "accountId",a.status AS "accountStatus" FROM employees e LEFT JOIN accounts a ON a.employee_id=e.id AND a.principal_type='EMPLOYEE' WHERE e.id=$1`,[p.data.employeeId])).rows[0];if(!person)return reply.status(404).send({code:"EMPLOYEE_NOT_FOUND"});const dependencyCategories=await dependencies(pool,p.data.employeeId);return reply.send({...person,dependencyCategories,blocked:dependencyCategories.length>0});});
  app.post("/admin/employees/:employeeId/remove",async(r,reply)=>{const actor=await guard(r,reply);if(!actor)return;const p=id.safeParse(r.params),b=removal.safeParse(r.body);if(!p.success||!b.success)return reply.status(400).send({code:"INVALID_REMOVAL"});const c=await pool.connect();try{await c.query("BEGIN");const person=(await c.query<{full_name:string}>("SELECT full_name FROM employees WHERE id=$1 AND removed_at IS NULL FOR UPDATE",[p.data.employeeId])).rows[0];if(!person||person.full_name!==b.data.confirmationName)throw new Error("REJECTED");const deps=await dependencies(c,p.data.employeeId);if(deps.length)throw new Error("DEPENDENCY");await c.query("UPDATE employees SET removed_at=now(),removed_by_account_id=$2,removal_reason=$3,updated_at=now() WHERE id=$1",[p.data.employeeId,actor.id,b.data.reason]);await c.query("UPDATE accounts SET status='inactive',updated_at=now() WHERE employee_id=$1 AND principal_type='EMPLOYEE'",[p.data.employeeId]);await c.query("UPDATE auth_sessions SET revoked_at=now() WHERE account_id IN (SELECT id FROM accounts WHERE employee_id=$1 AND principal_type='EMPLOYEE') AND revoked_at IS NULL",[p.data.employeeId]);await c.query("INSERT INTO access_audit_events (id,actor_account_id,action,entity_type,entity_id,payload) VALUES ($1,$2,'employee.master.removed','employee',$3,$4::jsonb)",[randomUUID(),actor.id,p.data.employeeId,JSON.stringify({reason:b.data.reason,source:"manual"})]);await c.query("COMMIT");return reply.send({employeeId:p.data.employeeId,removed:true});}catch(e){await c.query("ROLLBACK");return reply.status(e instanceof Error&&e.message==="DEPENDENCY"?409:400).send({code:e instanceof Error&&e.message==="DEPENDENCY"?"PUBLISHED_ORGANIZATION_DEPENDENCY":"REMOVAL_REJECTED"});}finally{c.release();}});
}
