import { randomUUID } from "node:crypto";
import type { FastifyInstance, FastifyReply, FastifyRequest } from "fastify";
import type { Pool } from "pg";
import { z } from "zod";
import type { ApiConfig } from "../../config/env.js";
import { requirePrincipalFromCookie } from "../auth/authorization.js";
import { AuthError, AuthService, type AuthPrincipal } from "../auth/service.js";

const id = z.object({ employeeId: z.string().uuid() });
const editable = z.object({ fullName:z.string().trim().min(1), employeeNumber:z.string().trim().min(1), status:z.enum(["active","inactive","resigned"]), employmentStatus:z.string().trim().nullable(), organizationalUnitId:z.string().uuid().nullable(), positionId:z.string().uuid().nullable(), employmentType:z.string().trim().nullable(), functionalPosition:z.string().trim().nullable(), structuralPosition:z.string().trim().nullable(), email:z.string().trim().email().nullable(), phone:z.string().trim().max(50).nullable(), education:z.string().trim().nullable(), startedOn:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).nullable(), endedOn:z.string().regex(/^\d{4}-\d{2}-\d{2}$/).nullable(), reason:z.string().trim().min(1).max(500) });
const removal = z.object({ confirmationName:z.string().trim().min(1), reason:z.string().trim().min(1).max(500) });

export async function registerEmployeeMasterAdminRoutes(app: FastifyInstance, pool: Pool, config: ApiConfig) {
  if (!config.AUTH_ENCRYPTION_KEY) throw new Error("AUTH_ENCRYPTION_KEY is required for employee master routes");
  const auth = new AuthService(pool, config.AUTH_ENCRYPTION_KEY, config.AUTH_SESSION_TTL_HOURS, config.NODE_ENV === "production");
  const guard = async (request: FastifyRequest, reply: FastifyReply): Promise<AuthPrincipal | null> => { try { return await requirePrincipalFromCookie(auth, request.headers.cookie, "SUPER_ADMIN"); } catch (e) { if (e instanceof AuthError) { await reply.status(e.statusCode).send({code:e.code,message:e.message}); return null; } throw e; } };
  const audit = (actor: AuthPrincipal, action: string, employeeId: string, payload: object) => pool.query("INSERT INTO access_audit_events (id,actor_account_id,action,entity_type,entity_id,payload) VALUES ($1,$2,$3,'employee',$4,$5::jsonb)",[randomUUID(),actor.id,action,employeeId,JSON.stringify(payload)]);

  app.get("/admin/employees/:employeeId/source-snapshots", async (request, reply) => { const actor=await guard(request,reply); if(!actor)return;const p=id.safeParse(request.params);if(!p.success)return reply.status(400).send({code:"INVALID_EMPLOYEE_ID",message:"ID pegawai tidak valid."}); const result=await pool.query(`SELECT s.id,s.source_filename AS "sourceFilename",s.source_sheet AS "sourceSheet",s.imported_at AS "importedAt",s.unmodeled_source_data AS "unmodeledSourceData" FROM employee_import_source_snapshots s WHERE s.employee_id=$1 ORDER BY s.imported_at DESC`,[p.data.employeeId]); return reply.send({items:result.rows.map(row=>({...row,importedAt:row.importedAt.toISOString()}))}); });

  app.patch("/admin/employees/:employeeId", async (request, reply) => { const actor=await guard(request,reply); if(!actor)return; const p=id.safeParse(request.params), b=editable.safeParse(request.body); if(!p.success||!b.success)return reply.status(400).send({code:"INVALID_EMPLOYEE_EDIT",message:"Data pegawai tidak valid."}); const before=await pool.query("SELECT row_to_json(e) AS value FROM employees e WHERE id=$1",[p.data.employeeId]); if(!before.rows[0])return reply.status(404).send({code:"EMPLOYEE_NOT_FOUND",message:"Pegawai tidak ditemukan."}); const v=b.data; try { const result=await pool.query(`UPDATE employees SET full_name=$2,employee_number=$3,status=$4,employment_status=$5,organizational_unit_id=$6,position_id=$7,employment_type=$8,functional_position=$9,structural_position=$10,email=$11,phone=$12,education=$13,started_on=$14,ended_on=$15,updated_at=now() WHERE id=$1 RETURNING id`,[p.data.employeeId,v.fullName,v.employeeNumber,v.status,v.employmentStatus,v.organizationalUnitId,v.positionId,v.employmentType,v.functionalPosition,v.structuralPosition,v.email?.toLowerCase()??null,v.phone,v.education,v.startedOn,v.endedOn]); await audit(actor,"employee.master.updated",p.data.employeeId,{before:before.rows[0].value,after:v,changedFields:Object.keys(v).filter(k=>k!=="reason"),reason:v.reason,source:"manual"}); return reply.send({employeeId:result.rows[0].id,accountEmailChanged:false}); } catch { return reply.status(409).send({code:"EMPLOYEE_EDIT_CONFLICT",message:"NIP atau referensi pegawai tidak dapat digunakan."}); } });
  app.post("/admin/employees/:employeeId/remove-preview", async (request, reply) => { const actor=await guard(request,reply); if(!actor)return; const p=id.safeParse(request.params); if(!p.success)return reply.status(400).send({code:"INVALID_EMPLOYEE_ID",message:"ID pegawai tidak valid."}); const r=await pool.query(`SELECT e.full_name AS "fullName",e.removed_at AS "removedAt",a.id AS "accountId",a.status AS "accountStatus",(SELECT count(*)::int FROM organization_memberships m JOIN organization_change_sets c ON c.id=m.change_set_id WHERE m.employee_id=e.id AND c.status='PUBLISHED') AS "publishedAssignments" FROM employees e LEFT JOIN accounts a ON a.employee_id=e.id AND a.principal_type='EMPLOYEE' WHERE e.id=$1`,[p.data.employeeId]); if(!r.rows[0])return reply.status(404).send({code:"EMPLOYEE_NOT_FOUND",message:"Pegawai tidak ditemukan."}); return reply.send(r.rows[0]); });
  app.post("/admin/employees/:employeeId/remove", async (request, reply) => { const actor=await guard(request,reply);if(!actor)return;const p=id.safeParse(request.params),b=removal.safeParse(request.body);if(!p.success||!b.success)return reply.status(400).send({code:"INVALID_REMOVAL",message:"Konfirmasi penghapusan dari master tidak valid."}); const client=await pool.connect();try {await client.query("BEGIN");const e=await client.query<{full_name:string}>("SELECT full_name FROM employees WHERE id=$1 AND removed_at IS NULL FOR UPDATE",[p.data.employeeId]);if(!e.rows[0])throw new Error("NOT_FOUND");if(e.rows[0].full_name!==b.data.confirmationName)throw new Error("CONFIRMATION");const dep=await client.query<{count:number}>("SELECT count(*)::int AS count FROM organization_memberships m JOIN organization_change_sets c ON c.id=m.change_set_id WHERE m.employee_id=$1 AND c.status='PUBLISHED'",[p.data.employeeId]);if(dep.rows[0]!.count>0)throw new Error("DEPENDENCY");await client.query("UPDATE employees SET removed_at=now(),removed_by_account_id=$2,removal_reason=$3,updated_at=now() WHERE id=$1",[p.data.employeeId,actor.id,b.data.reason]);await client.query("UPDATE accounts SET status='inactive',updated_at=now() WHERE employee_id=$1 AND principal_type='EMPLOYEE'",[p.data.employeeId]);await client.query("UPDATE auth_sessions SET revoked_at=now() WHERE account_id IN (SELECT id FROM accounts WHERE employee_id=$1 AND principal_type='EMPLOYEE') AND revoked_at IS NULL",[p.data.employeeId]);await client.query("INSERT INTO access_audit_events (id,actor_account_id,action,entity_type,entity_id,payload) VALUES ($1,$2,'employee.master.removed','employee',$3,$4::jsonb)",[randomUUID(),actor.id,p.data.employeeId,JSON.stringify({reason:b.data.reason,source:"manual"})]);await client.query("COMMIT");return reply.send({employeeId:p.data.employeeId,removed:true});}catch(e){await client.query("ROLLBACK");const m=e instanceof Error?e.message:"";return reply.status(m==="DEPENDENCY"?409:400).send({code:m==="DEPENDENCY"?"PUBLISHED_ORGANIZATION_DEPENDENCY":"REMOVAL_REJECTED",message:m==="DEPENDENCY"?"Keanggotaan organisasi pada revisi published harus diselesaikan lebih dulu.":"Penghapusan dari Employee Master ditolak."});}finally{client.release();} });
}
